services:
  postgres:
    image: postgres:16
    container_name: kinhdo-postgres
    restart: unless-stopped

    env_file:
      - ./be-qlda/.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_qlda
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: